### ISSUE TITLE
⚠️ Snake case issue in v0.17.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#265]
v0.17.0 of this package is broken -> it transforms the attributes of the user documents

example, if I try to push this document

```json
[
  { "id": 2,    "my_title": "Pride and Prejudice" },
]
```

it will push the following document

```json
[
  { "id": 2,    "myTitle": "Pride and Prejudice" },
]
```

which is not what we expect, the document of the user should stay unchanged

@brunoocasali, since you introduced the snake case compatibility (we expected for settings only, not the documents) in https://github.com/meilisearch/meilisearch-ruby/pull/237, do you know how to fix this?

I tried to revert the PR, but GitHub does not want to apply a revert here.

We also should add a test importing a document with snake case attributes and check this is well imported to MeiliSearch.

**Comment by brunoocasali** [comment]
Yes, @curquiza I will look to that :)

**Comment by curquiza** [comment]
Thank you so much 🙏 it's the beginning of the night for me, not easy to do a smart fix for my brain 😂

**Comment by brunoocasali** [comment]
hahah don’t worry!

Just to check, there are other endpoints with this problem? Or only when you try to push documents?

**Comment by curquiza** [comment]
If I'm correct only when you try to add, but also update, documents

**Comment by brunoocasali** [comment]
@curquiza first of all sorry about this :/

This use case was not perceived when I implemented the feature because I didn’t check if the other requests were properly covered by tests, in this case, the "add document" method wasn’t checking if the "document body" is maintained after the insert.

The problem happens because sometimes we need the body to be "switched" to the camelCase (settings/indexes requests) and sometimes we don't want that (adding documents) but they share the same request configuration.

I'm thinking of a good way to solve this.

Sorry again about the inconvenience :/

**Comment by curquiza** [comment]
Not a problem, I should have asked for better tests 😄 Bugs happen!
Thanks for the fix!!
