### ISSUE TITLE
Improve the gem's public api by removing the bang operator in some methods

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-ruby#288]
Original discussion https://github.com/meilisearch/meilisearch-ruby/pull/273/files#r779759981

Today we use `!`(bang) operator in some particular cases eg. `create_index!`, `add_documents!`, these methods have something in common, *they wait for the task completion*.

After v0.25.0 index creations are totally async, so they respond with a task object not an index anymore. Anyway, what is the real problem here is the usage of bang makes a lot of difference and the typing structure is close to the other methods.

You could type `create_index` and get a `task` as a response, or  
You could type `create_index!` and get an `index` as a response.

The proposal here is to remove this syntax in order to provide something more clear to prevent such mistakes like:

`create_index('movies', sync: true)`, `create_index('movies', wait: true)`, `create_index('movies', wait_for_completion: true)`, in a way that if we don’t pass such param we know that it will respond with default `task` object.

**Comment by Smartmind12** [comment]
@brunoocasali Would you want the current `create_index` to be `create_index('movies', sync: true)` or `create_index('movies', wait: true)`?

**Comment by brunoocasali** [comment]
Hi @Smartmind12 I don't have a favorite here, but I think we can go for the `wait: true` version :)

**Comment by Smartmind12** [comment]
@brunoocasali I have made the changes with the PR ...Kindly review the same!

**Comment by yyamanoi1222** [comment]
@brunoocasali May i do this issue?

**Comment by brunoocasali** [comment]
Yes! @yyamanoi1222 of course!

**Comment by ellnix** [comment]
I was going through this issue (and associated pull requests) and wondering if this is the best way to do this.
- the `sync` option enters the options namespace (which is strictly speaking not under this gem's control), which will cause problems if meilisearch adds an option named `sync` in the future
- polymorphism with a flag is introduced to a lot of methods (not generally a best practice but not a big problem either)
- we deprecate existing behavior without a very good reason from a user's perspective, since passing a flag is not all that different from adding a bang

What if a new `MeiliSearch::Client::Task` class or the existing `MeiliSearch::Task` class could have instances which encapsulate the task hash that is currently returned from methods such as `create_index`? 

```ruby
task = Client.create_index('books')
task.class # => MeiliSearch::Task (not Hash)
task.status # => "processing"
task.await # => returns itself or raises timeout error
    .status # => "successful"
```

The equivalent to the old `create_index!` would be

```ruby
Client.create_index('books').await
```

It would allow a user to be sure that a task has completed without necessarily having to pause execution until it finishes by deferring the wait (could be significant in long tasks or in our test suites which have a lot of synchronous operations)
```ruby
def long_process
  sleep 0.5
end

Client.create_index('books', wait: true) # Waits for index to be created
long_process # Waits 0.5 seconds
# total wait: 0.5 seconds + time it takes to create index

task = Client.create_index('books')
long_process # Waits 0.5 seconds
task.await # Waits if the index still has not been created
# total wait: max(0.5 seconds, time it takes to create index)
```

This would also allow for better introspection of tasks once they are created for those who want that sort of control:
```ruby
task = Client.create_index('books')
logger = Logger.new($stdout)

if task.await.successful?
  logger.debug("Created meilisearch index 'books' successfully")
else
  logger.warn("Failed to create meilisearch index (task #{task.uid}) with #{task.error}")
end
```

**Comment by brunoocasali** [comment]
Hi @ellnix, I like your idea! 

This issue received a PR https://github.com/meilisearch/meilisearch-ruby/pull/441 in the past, but unfortunately, I did not have the time to merge it since my priorities have drastically changed.

In any case, after reading your suggestion, it will bring much value to the user compared to the one I suggested, and it will probably be easier to understand.

To approach that change, I believe we could introduce it in this order: 

- [ ] 1º Introduce the new way (the class and the await/wait_for method) 
- [ ] 2º In another PR, introduce an alert to the users who will still be using the old way (with the bang operator)
- [ ] 3º Raise a PR into the `meilisearch-rails` where we change the approach to use the new one (+ update meilisearch-ruby on it).
- [ ] 4º Remove the usage of the bang operator here.


FYI: I think using this synchronous method is not good and should even exist. My opinion is spread across multiple places in the meilisearch repos, but to make a TL;DR, awaiting synchronously for long-running tasks could break your system.

**Comment by ellnix** [comment]
>     * [ ]  1º Introduce the new way (the class and the await/wait_for method)
So we should have a `MeiliSearch::Client::Task` class? Just to be clear about whether or not we repurpose `MeiliSearch::Task` somehow or whether you have other ideas about the class name & namespace.

I agree on the steps to integrate this change, and I can implement it if you would like.

> FYI: I think using this synchronous method is not good and should even exist. My opinion is spread across multiple places in the meilisearch repos, but to make a TL;DR, awaiting synchronously for long-running tasks could break your system.

I also agree to be honest that you would pretty much never want to do this (except for testing). My rationale for even supporting it is to trust that developers will not call `await` until they **have** to, or only for short tasks. 

I actually had another idea that I did not suggest here because I thought it would be too radical: we could implement a callback using the recent [async gem](https://github.com/socketry/async) similar to javascript promises.
```ruby
client.create_index('books').then do |task|
  if task.successful?
    logger.debug("Created meilisearch index 'books' successfully")
  else
    logger.warn("Failed to create meilisearch index (task #{task.uid}) with #{task.error}")
  end
end
```
I have never used this gem before, but I have seen examples of it around the release of ruby 3 since this gem was a major inspiration behind the new asynchronous ruby 3 features.

Another idea would be for meilisearch to provide a webhook or some kind of socket that can notify an app when the indexing is done (without needing to poll it), I don't know if that does or doesn't exist. Either way it is way outside the scope of this gem.

**Comment by brunoocasali** [comment]
> Another idea would be for meilisearch to provide a webhook or some kind of socket that can notify an app when the indexing is done (without needing to poll it), I don't know if that does or doesn't exist. Either way it is way outside the scope of this gem.

Yes, that's something we would love to have, although as far as I remember, no one has come with a feature request yet regarding that.

> recent [async gem](https://github.com/socketry/async) similar to javascript promises. 

I don't think we need that TBH, and I agree with you it would be too radical haha.

Regarding the class name:

I think we could introduce a new class instead of reusing Task One, just to avoid any change. What I'm thinking right now (but you could try a different approach, of course) is to have a new namespace like `::Resources::` or `::Models` or something like that, to be a place where we could add those kinds of POROs. 

Because I foresee we using it for other kinds of data, like Index, Settings, and such...

**Comment by bb** [comment]
FWIW, from all ideas discussed above, I like `Task#await` most. I don't care about the exact namespace of the Task class.
