### ISSUE TITLE
Random fail when running tests in CI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#60]
<img width="1287" alt="Capture d’écran 2020-06-24 à 15 30 21" src="https://user-images.githubusercontent.com/20380692/85565721-b1260b00-b62f-11ea-8f3d-06f95709faf1.png">

See [this job](https://github.com/meilisearch/meilisearch-ruby/runs/803506021?check_suite_focus=true) for example.

**Comment by Chhekur** [comment]
closes [#98 ](https://github.com/meilisearch/meilisearch-ruby/pull/98)

**Comment by curquiza** [comment]
Still need a fix

**Comment by curquiza** [comment]
We did not succeed to reproduce the issue. I close it but feel free to reopen if needed

**Comment by alallema** [comment]
Last time bug appears on [1-04-2021](https://github.com/meilisearch/meilisearch-ruby/runs/2236239702?check_suite_focus=true)
I could reproduce this error on ubuntu 20.04:
<details>
    <summary>Screenshot</summary>
<img width="1542" alt="Capture d’écran 2021-04-26 à 16 37 54" src="https://user-images.githubusercontent.com/16155041/116112062-807f8980-a6b7-11eb-9d12-c180a7f19f05.png">
</details>
This issue arise from an improperly handled exception in `Net::HTTP`

[This article](https://em1l1o.github.io/posts/trace_down_a_memory_leak_issue), for more details with a somewhat related issue

Fixed by ruby/ruby#3164
